"""Add StudentBatchMap and batch_id to sessions

Revision ID: ce4798e5ff78
Revises: c7e4d36ad6a3
Create Date: 2026-08-06 17:45:43.339591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce4798e5ff78'
down_revision: Union[str, Sequence[str], None] = 'c7e4d36ad6a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_batch_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'batch_id', name='uq_student_batch')
    )
    op.create_index(op.f('ix_student_batch_map_id'), 'student_batch_map', ['id'], unique=False)
    op.add_column('session_embeddings', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_session_embeddings_batch_id'), 'session_embeddings', ['batch_id'], unique=False)
    op.create_foreign_key(None, 'session_embeddings', 'batches', ['batch_id'], ['id'], ondelete='CASCADE')
    op.add_column('sessions', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sessions_batch_id'), 'sessions', ['batch_id'], unique=False)
    op.create_foreign_key(None, 'sessions', 'batches', ['batch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_index(op.f('ix_sessions_batch_id'), table_name='sessions')
    op.drop_column('sessions', 'batch_id')
    op.drop_constraint(None, 'session_embeddings', type_='foreignkey')
    op.drop_index(op.f('ix_session_embeddings_batch_id'), table_name='session_embeddings')
    op.drop_column('session_embeddings', 'batch_id')
    op.drop_index(op.f('ix_student_batch_map_id'), table_name='student_batch_map')
    op.drop_table('student_batch_map')
    # ### end Alembic commands ###
