"""Add detailed scores to sessions

Revision ID: d034fb22747d
Revises: 28f18348741c
Create Date: 2026-08-06 02:43:10.513557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd034fb22747d'
down_revision: Union[str, Sequence[str], None] = '28f18348741c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('fluency_score', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('english_proficiency_score', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('communication_impact_score', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('vocal_engagement_score', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('physical_presence_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'physical_presence_score')
    op.drop_column('sessions', 'vocal_engagement_score')
    op.drop_column('sessions', 'communication_impact_score')
    op.drop_column('sessions', 'english_proficiency_score')
    op.drop_column('sessions', 'fluency_score')
    op.drop_column('sessions', 'confidence_score')
    # ### end Alembic commands ###
