"""Add ApprovalStatus to User

Revision ID: d08adb7adcf3
Revises: d034fb22747d
Create Date: 2026-08-06 17:10:06.290925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd08adb7adcf3'
down_revision: Union[str, Sequence[str], None] = 'd034fb22747d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE approvalstatus AS ENUM ('pending', 'approved', 'rejected', 'hold');")
    op.add_column('users', sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'hold', name='approvalstatus'), server_default='pending', nullable=False))
    op.add_column('users', sa.Column('reviewed_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('review_note', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['reviewed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'review_note')
    op.drop_column('users', 'reviewed_at')
    op.drop_column('users', 'reviewed_by')
    op.drop_column('users', 'status')
    op.execute("DROP TYPE approvalstatus;")
    # ### end Alembic commands ###
