"""Add assigned_admin_id to Course

Revision ID: dd5f9743edb5
Revises: 6cf5ce273603
Create Date: 2026-08-25 18:53:53.826029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd5f9743edb5'
down_revision: Union[str, Sequence[str], None] = '6cf5ce273603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('assigned_admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'users', ['assigned_admin_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'assigned_admin_id')
    # ### end Alembic commands ###
